[tool.poetry]
name = "bird-finder-app"
version = "0.1.0"
description = "eBird API information"
authors = ["Connor <flocka_birdz@pm.me>"]

[tool.poetry.dependencies]
python = "^3.10"
dlt = "^0.3.12"
duckdb = "^0.8.0"
sqlmesh = "^0.28.0"
python-dotenv = "^0.20.0"
click = "^8.1.1"
colorama = "^0.4.4"
pandas = "^1.1.0"
s3fs = "^2023.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.6.0"]
build-backend = "poetry.core.masonry.api"